### ISSUE TITLE
How to create a custom named PVC ?

### ISSUE THREAD

**Issue by ksingh7** [openshift/aws-efs-operator#41]
Hi 

Everything works in my setup, however, i have one question, how can I create a custom named PVC when creating a shared volume.

```
apiVersion: aws-efs.managed.openshift.io/v1alpha1
kind: SharedVolume
metadata:
  name: okd-efs-1
  namespace: 3scale
spec:
  accessPointID: fsap-024004066af9dfb96
  fileSystemID: fs-269990f7
status:
  claimRef:
    apiGroup: ''
    kind: PersistentVolumeClaim
    name: pvc-okd-efs-1
  phase: Ready

```
- Here are the PVC
```
NAME                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-okd-efs-1           Bound     pv-3scale-okd-efs-1                        1Gi        RWX            efs-sc         14m
```
- Here are the PV
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS   REASON   AGE
pv-3scale-okd-efs-1                        1Gi        RWX            Retain           Bound    3scale/pvc-okd-efs-1           efs-sc                  15m
```

Suppose i wanted to have a PVC with name `Shared-Storage` how can i do that ?

**Comment by ksingh7** [comment]
So here is how i manged to do that
- Do not create sharedvolume instead create PV/PVC manually using the below YAML files

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-storage
spec:
  storageClassName: efs-sc
  capacity:
    storage: 1Gi # Doesn't really matter, as EFS does not enforce it anyway
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: YOUR_FS_ID_HERE


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage
  namespace: 3scale
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc
```
